-- 50. 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기 Level 3

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT A.CAR_ID
                 FROM (SELECT *
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31') A
                 GROUP BY A.CAR_ID 
                 HAVING COUNT(A.CAR_ID) >= 5)
    AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC