-- 49. 오랜 기간 보호한 동물(1) Level 3

SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                         FROM ANIMAL_OUTS)
ORDER BY A.DATETIME
LIMIT 3