-- 44. 상품 별 오프라인 매출 구하기 Level 2

SELECT A.PRODUCT_CODE, SUM(B.SALES_AMOUNT)*A.PRICE AS SALES
FROM PRODUCT A INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE ASC
